#!/bin/sh

hou=0
w | grep console | awk '{print $5}' | grep : > /dev/null 2>&1
ret=$?
if [ $ret -eq 0 ]; then
	min=$(w | grep console | awk '{print $5}' | cut -f 2 -d : )
	hou=$(w | grep console | awk '{print $5}' | cut -f 1 -d : )
else
	min=$(w | grep console | awk '{print $5}')
fi
if w | grep console | awk '{print $5}' > /dev/null ; then
	hou=0
	min=0
fi
uname=$(uname -a | awk '{print $2}' | rev | cut -c 11- | rev)
time=$(date +%H:%M)
if [ "$hou" -lt 10 ]; then
	if [ "$min" -lt 10 ]; then
		if [ "$hou" -lt 1 ]; then
			uptime="0$hou:0$min"
		else
			uptime="0$hou:$min"
		fi
	else
		uptime="0$hou:$min"
	fi
else
	if [ "$min" -lt 10 ]; then
		uptime="$hou:0$min"
	else
		uptime="$hou:$min"
	fi
fi
c0="$(tput setaf 4)"
nc="$(tput sgr0)"
cat <<EOF
${c0}             LE - /
${c0}                 /
${c0}       .::    .:/ .      .::  user   : ${nc}${USER}@${uname}
${c0}    +:+:+   +:    +:  +:+:+
${c0}     +:+   +:    +:    +:+    time   : ${nc}${time}
${c0}    #+#   #+    #+    #+#     uptime : ${nc}${uptime}
${c0}   #+#   ##    ##    #+#
${c0}  ###    #+. /#+    ###
${c0}            /
${c0}           /
EOF
